version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: 'Mounted from ${CVAT_MOUNT:-/home/ubuntu/dtpl-ai-data-labelling} host directory'
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: ${CVAT_MOUNT:-/home/ubuntu/dtpl-ai-data-labelling}
      o: bind
